# configuration for the librispeech dataset with clearml

# task initialisation
project_name: 'wav2vec2_kenlm_pipeline'
task_name: 'build_lm'
dataset_name: 'librispeech_v2_build_lm'
output_url: 's3://experiment-logging'
dataset_project: 'datasets/librispeech'

# get to the build_lm.sh script path
script_task_id: 'c70c443505414744a772882d9137ba24'

# arguments corresponding to the transform_pkl_to_txt.py
dataset_pkl_task_id: 'fdb1e1471ebb4b8dbf4f599080401819' # pkl files

# kenlm id
kenlm_id: 'e429669809e5486784f0ace5cf182adb'

train_pkl: 'pkl/librispeech_train.pkl'
dev_pkl: 'pkl/librispeech_dev.pkl'
script_path: 'build_lm.sh'
root_path: ''
txt_filepath: 'root/lm/librispeech.txt'
n_grams: '5'
dataset_name_: 'librispeech'

# queue name
queue: 'cpu-only'